### ISSUE TITLE
Error infalting class com.alihafizji.splitimageview.SplitImageView

### ISSUE THREAD

**Issue by awais-abbas-geekybugs** [aliHafizji/SplitImageView#3]
When i set foregroundSrc="@drawable/dummy_3" it throws exception  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.example.cameraxbasic/com.android.example.cameraxbasic.BeautificationActivity}: android.view.InflateException: Binary XML file line #10: Binary XML file line #10: Error inflating class com.alihafizji.splitimageview.SplitImageView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2747)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2808)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6375)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
     Caused by: android.view.InflateException: Binary XML file line #10: Binary XML file line #10: Error inflating class com.alihafizji.splitimageview.SplitImageView
     Caused by: android.view.InflateException: Binary XML file line #10: Error inflating class com.alihafizji.splitimageview.SplitImageView
     Caused by: java.lang.reflect.InvocationTargetException

**Comment by awais-abbas-geekybugs** [comment]
Okay so it was pretty quick after posting issue i solved this by setting background and foreground sources with java and i still get the issue when i set these sources from xml file
